<a href="https://colab.research.google.com/github/leomensah/TENSORFLOW/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


# Initialization of Tensors
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
x = tf.constant([[1,2,3], [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x = tf.ones((3,3))
print(x)
x = tf.zeros((2,3))
print(x)
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
## Random Normal distribution
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

x = tf.range(9)
print(x)

x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor(
[[-0.06967314 -0.14190735 -0.41328487]
 [ 0.09124216 -0.15155008 -0.50286525]
 [ 0.34172484  1.7169183   0.83328325]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.02106512 0.00647044 0.07762408]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
x = tf.cast(x, dtype=tf.float64)
print(x)
# tf.float (16, 32, 64), tf.int(8, 16, 32, 64), tf.bool

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


### **Adding of Tensors**

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


### **Subtract Tensors**

In [ ]:
z = tf.subtract(x, y)
print(z)
z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


### **Division of Tensors**

In [ ]:
z = tf.divide(x, y)
print(z)

z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


### **Multiplication of Tensors**

In [ ]:
z = tf.multiply(x, y)
z = x * y
print(z)
z = tf.tensordot(x, y, axes=1)
print(z)


z = x ** 5
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [ ]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

z = tf.matmul(x, y)
print(z)

z = x @ y
print(z)

tf.Tensor(
[[ 0.27553022 -1.2623867   1.6870717   1.7062398 ]
 [ 1.09977    -0.7940798   0.24670082  1.0057094 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.27553022 -1.2623867   1.6870717   1.7062398 ]
 [ 1.09977    -0.7940798   0.24670082  1.0057094 ]], shape=(2, 4), dtype=float32)


In [ ]:
# Indexing ni Tensorflow

x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [ ]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)

x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

print(x[0, :])
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### **Reshaping**

In [ ]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


## **Building and training Neural Networks**

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 784).astype('float32') / 255.0
x_test = x_test.reshape(-1, 28*28).astype('float32') / 255.0

# Sequential API (Very convenient, not very flexible)
model = keras.Sequential(
    [
     layers.Dense(512, activation='relu'),
     layers.Dense(255, activation='relu', name='my_layer'),
     layers.Dense(10)
    ]
)

# model = keras.Model(inputs=model.inputs, outputs=[model.layers[-2].output])
model = keras.Model(inputs=model.inputs, outputs=model.get_layer('my_layer').output])
feature = model.predict(x_train)
print(feature.shape)


model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = keras.optimizers.Adam(lr=0.001),
    metrics = ["accuracy"]
)


model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


1875/1875 - 9s - loss: 0.1854 - accuracy: 0.9440 - 9s/epoch - 5ms/step
Epoch 2/5
1875/1875 - 9s - loss: 0.0790 - accuracy: 0.9757 - 9s/epoch - 5ms/step
Epoch 3/5
1875/1875 - 9s - loss: 0.0541 - accuracy: 0.9829 - 9s/epoch - 5ms/step
Epoch 4/5
1875/1875 - 9s - loss: 0.0417 - accuracy: 0.9867 - 9s/epoch - 5ms/step
Epoch 5/5
1875/1875 - 9s - loss: 0.0325 - accuracy: 0.9895 - 9s/epoch - 5ms/step
313/313 - 1s - loss: 0.0697 - accuracy: 0.9814 - 851ms/epoch - 3ms/step


[0.06969050318002701, 0.9814000129699707]

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation='relu'))
print(model.summary())
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 512)               401920    
                                                                 
Total params: 401,920
Trainable params: 401,920
Non-trainable params: 0
_________________________________________________________________
None
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 512)               401920    
                                                                 
 dense_7 (Dense)             (None, 256)               131328    
                                                                 
 dense_8 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818

In [ ]:
### Functional API

inputs = keras.Input(shape=(784))
x = layers.Dense(512, activation='relu')(inputs)
x = layers.Dense(256, activation='relu')(x)
outputs = layers.Dense(10, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer = keras.optimizers.Adam(lr=0.001),
    metrics = ["accuracy"]
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 784)]             0         
                                                                 
 dense_9 (Dense)             (None, 512)               401920    
                                                                 
 dense_10 (Dense)            (None, 256)               131328    
                                                                 
 dense_11 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


1875/1875 - 11s - loss: 0.1879 - accuracy: 0.9419 - 11s/epoch - 6ms/step
Epoch 2/5
1875/1875 - 9s - loss: 0.0805 - accuracy: 0.9738 - 9s/epoch - 5ms/step
Epoch 3/5
1875/1875 - 9s - loss: 0.0547 - accuracy: 0.9823 - 9s/epoch - 5ms/step
Epoch 4/5
1875/1875 - 9s - loss: 0.0420 - accuracy: 0.9865 - 9s/epoch - 5ms/step
Epoch 5/5
1875/1875 - 9s - loss: 0.0322 - accuracy: 0.9894 - 9s/epoch - 5ms/step
313/313 - 1s - loss: 0.0901 - accuracy: 0.9771 - 824ms/epoch - 3ms/step


[0.09006597101688385, 0.9771000146865845]

## **Convolutional Neural Networks**

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# model = keras.Sequential(
#     [
#      keras.Input(shape=(32, 32, 3)), 
#      layers.Conv2D(32, 3, padding='valid', activation='relu'),
#      layers.MaxPooling2D(pool_size=(2,2)),
#      layers.Conv2d(64, 3, activation='relu'),
#      layers.MaxPooling2D(),
#      layers.Conv2D(128, 3, activation='relu'),
#      layers.Dense(64, activation='relu'),
#      layers.Dense(10)
#     ]
# )

# print(model.summary())

def my_model():
  inputs = keras.Input(shape=(32, 32, 3))
  x = layers.Conv2D(32, 3)(inputs)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.MaxPooling2D()(x)
  x = layers.Conv2D(64, 5, padding='same')(x)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.Conv2D(128, 3)(x)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.Flatten()(x)
  x = layers.Dense(64, activation='relu')(x)
  outputs = layers.Dense(10)(x)
  model = keras.Model(inputs=inputs, outputs=outputs)
  return model

model = my_model()


model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/10
782/782 - 219s - loss: 1.3321 - accuracy: 0.5270 - 219s/epoch - 280ms/step
Epoch 2/10
782/782 - 225s - loss: 0.9154 - accuracy: 0.6769 - 225s/epoch - 288ms/step
Epoch 3/10
782/782 - 218s - loss: 0.7541 - accuracy: 0.7358 - 218s/epoch - 279ms/step
Epoch 4/10
782/782 - 217s - loss: 0.6446 - accuracy: 0.7747 - 217s/epoch - 278ms/step
Epoch 5/10
782/782 - 217s - loss: 0.5550 - accuracy: 0.8079 - 217s/epoch - 277ms/step
Epoch 6/10
782/782 - 216s - loss: 0.4759 - accuracy: 0.8354 - 216s/epoch - 277ms/step
Epoch 7/10
782/782 - 216s - loss: 0.4003 - accuracy: 0.8613 - 216s/epoch - 277ms/step
Epoch 8/10
782/782 - 217s - loss: 0.3356 - accuracy: 0.8871 - 217s/epoch - 277ms/step
Epoch 9/10
782/782 - 217s - loss: 0.2804 - accuracy: 0.9056 - 217s/epoch - 278ms/step
Epoch 10/10
782/782 - 217s - loss: 0.2341 - accuracy: 0.9212 - 217s/epoch - 277ms/step
157/157 - 10s - loss: 1.1263 - accuracy: 0.6837 - 10s/epoch - 67ms/step


[1.126285433769226, 0.6837000250816345]

BUILDING A CONVOLUTIONAL NEURAL NETWORK WITH THE TENSORFLOW SUBCLASSING API

TENSORFLOW SUBCLASSING

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

physical_devices = tf.config.list_physical_devices("GPU")
print(physical_devices)
tf.config.experimental.set_memory_growth(physical_devices[0], True)

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28, 28, 1).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28, 28, 1).astype("float32") / 255.0

#print(x_train.shape, x_test.shape)
# CNN -> BatchNOrm -> ReLU (Common structure)

class CNNBlock(layers.Layer):
  def __init__(self, out_channels, kernel_size=3):
    super(CNNBlock, self).__init__()
    self.conv = layers.Conv2D(out_channels, kernel_size, padding='same')
    self.bn = layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv(input_tensor)
    x = self.bn(x, training=training)
    x = tf.nn.relu(x)
    return x

model = keras.Sequential(
    [
     CNNBlock(32),
     CNNBlock(64),
     CNNBlock(128),
     layers.Flatten(),
     layers.Dense(10)
    ]
)

model.compile(
    optimizer=keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"]
)


model.fit(x_train, y_train, batch_size=64, epochs=3, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2) 


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Epoch 1/3
938/938 - 22s - loss: 0.5508 - accuracy: 0.9452 - 22s/epoch - 23ms/step
Epoch 2/3
938/938 - 11s - loss: 0.0938 - accuracy: 0.9814 - 11s/epoch - 11ms/step
Epoch 3/3
938/938 - 11s - loss: 0.0364 - accuracy: 0.9891 - 11s/epoch - 11ms/step
157/157 - 1s - loss: 0.0603 - accuracy: 0.9846 - 939ms/epoch - 6ms/step


[0.06026289239525795, 0.9846000075340271]

In [ ]:
class ResBlock(layers.Layer):
  def __init__(self, channels):
    super(ResBlock, self).__init__()
    self.cnn1 = CNNBlock(channels[0])
    self.cnn2 = CNNBlock(channels[1])
    self.cnn3 = CNNBlock(channels[2])
    self.pooling = layers.MaxPooling2D()
    self.identity_mapping = layers.Conv2D(channels[1], 1, padding='same')

  def call(self, input_tensor, training=False):
    x = self.cnn1(input_tensor, training=training)
    x = self.cnn2(x, training=training)
    x = self.cnn3(
        x + self.identity_mapping(input_tensor), training=training
    )
    return self.pooling(x)

class ResNet_Like(keras.Model):
  def __init__(self, num_classes=10):
    super(ResNet_Like, self).__init__()
    self.block1 = ResBlock([32, 32, 64])
    self.block2 = ResBlock([128, 128, 256])
    self.block3 = ResBlock([128, 256, 512])
    self.pool = layers.GlobalAveragePooling2D()
    self.classifier = layers.Dense(num_classes)

  def call(self, input_tensor, training=False):
    x = self.block1(input_tensor, training=training)
    x = self.block2(x, training=training)
    x = self.block3(x, training=training)
    x = self.pool(x)
    return self.classifier(x)

  def model(self):
    x = keras.Input(shape=(28, 28, 1))
    return keras.Model(inputs=[x], outputs=self.call(x))

model = model = ResNet_Like(num_classes=10)

model.compile(
    optimizer=keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"]
)


model.fit(x_train, y_train, batch_size=64, epochs=3, verbose=2)
print(model.model().summary())
model.evaluate(x_test, y_test, batch_size=64, verbose=2) 

Epoch 1/3
938/938 - 25s - loss: 0.0845 - accuracy: 0.9750 - 25s/epoch - 27ms/step
Epoch 2/3
938/938 - 23s - loss: 0.0360 - accuracy: 0.9887 - 23s/epoch - 25ms/step
Epoch 3/3
938/938 - 24s - loss: 0.0264 - accuracy: 0.9921 - 24s/epoch - 25ms/step
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 28, 28, 1)]       0         
                                                                 
 res_block (ResBlock)        (None, 14, 14, 64)        28640     
                                                                 
 res_block_1 (ResBlock)      (None, 7, 7, 256)         526976    
                                                                 
 res_block_2 (ResBlock)      (None, 3, 3, 512)         1839744   
                                                                 
 global_average_pooling2d (G  (None, 512)              0         
 lobalAverage

[0.06407003104686737, 0.9794999957084656]

## **TENSORFLOW CUSTOME LAYERS**

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

physical_devices = tf.config.list_physical_devices("GPU")
print(physical_devices)
tf.config.experimental.set_memory_growth(physical_devices[0], True)

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28, 28, 1).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28, 28, 1).astype("float32") / 255.0


class Dense(layers.Layer):
  def __init__(self, units):
    super(Dense, self).__init__()
    self.units = units
    
  def build(self, input_shape):
    self.w = self.add_weight(
        name='w',
        shape=(input_shape[-1], self.units),
        initializer='random_normal',
        trainable=True,
    )

    self.b = self.add_weight(
        name='b', shape=(self.units,),
        initializer='zeros',
        trainable=True
    )

  def call(self, inputs):
    return tf.matmul(inputs, self.w) + self.b

class MyReLU(layers.Layer):
  def __init__(self):
    super(MyReLU, self).__init__()

  def call(self, x):
    return tf.math.maximum(x, 0)

class MyModel(keras.Model):
  def __init__(self, num_classes=10):
    super(MyModel, self).__init__()
    self.dense1 = Dense(64)
    self.dense2 = Dense(num_classes)
    self.relu = MyReLU()

  def call(self, input_tensor):
    x = self.relu(self.dense1(input_tensor))
    return self.dense2(x)

model = MyModel()
model.compile(
    optimizer=keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"]
)

model.evaluate(x_test, y_test, batch_size=64, verbose=2) 

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


InvalidArgumentError: ignored